### ISSUE TITLE
[feature request] sending response to a single connection

### ISSUE THREAD

**Issue by araker** [schwarzkopfb/sse-broadcast#3]
Hi, I'm working on implementing a response for the Last-Event-ID header. When a client reconnects and the last-event-id header is present it would be convenient to have a method in sse-broadcast to send a message to that single client.

**Comment by schwarzkopfb** [comment]
Hey @araker!

I appreciate your feedback, and I accept that it would be a great extension of `sse-broadcast` to support the `last-event-id` header. However this introduces some unintended complexity; so this change requires appropriate planning.
To be able to target clients sticked to a given event id (at a specified point of the event-stream), we need to - at least temporarly - store event ids _per client_ on the server, which requires an abstract and centralised solution for server-side client state management.

I don't have a thoroughgoing solution for this use-case, but I'm open to any suggestion to implement this in a clean, maintainable and mature way.

**Comment by araker** [comment]
Hi @schwarzkopfb,  

I agree that for the last-event-id to work you need to save the id's on the server, I already use redis to save the outgoing event ids and retrieve the correct range of them when getting a last-event-id. I don't see this per se as a responsibility of your module though. 

So the only extra functionality I need is sending a message to a single client. I've created a hacked version of the publish function which works for my purpose. 
`/**
 * Send a message to a single connection
 *
 * @param {object} response to send the message to
 * @param {string|object} eventOrOptions Event name or an options object that specifies the message.
 * @param {string} [eventOrOptions.id]    Optional event identifier.
 * @param {string} [eventOrOptions.event] Event name.
 * @param {string} [eventOrOptions.data]  Optional event payload.
 * @param {string} [eventOrOptions.retry] Optional retry time for the receiver.
 * @param {*} [data] Optional event payload.
 * @param {function(Error?)} [callback]
 */
SSEBroadcaster.prototype.sendToSingle = function sendToSingle(res, eventOrOptions, data, callback) {
    var self     = this,
        compress = this.options.compression

    assert(arguments.length >= 2, '`sendToSingle()` requires at least two arguments')
    assert(eventOrOptions, 'second argument must specify the event name or options')

    if (typeof data === 'function') {
        callback = data
        data     = null
    }
    else if (!callback)
        callback = noop

    if (typeof eventOrOptions === 'object') {
        assert(!data, 'only one can be provided from `options` and `data`. Use `options.data` instead.')
        onprepared(eventOrOptions)
    }
    else if (typeof eventOrOptions === 'string')
        try {
            onprepared(prepareMessage(eventOrOptions, this.options.retry, data))
        }
        catch (ex) {
            this.emit('error', ex)
            process.nextTick(callback, ex)
            return this
        }
    else
        throw new TypeError('second argument must specify the event name or options')

    function onprepared(message) {
        try {
            oncomposed(composeMessage(message))
        }
        catch (ex) {
            self.emit('error', ex)
            process.nextTick(callback, ex)
            return this
        }
    }

    function oncomposed(message) {
        self._compress(res.req, res, function () {
            // write SSE response headers if possible
            if (!res._sseHeadersSent) {
                res._sseHeadersSent = true

                // disable response buffering to
                // flush chunks immediately after writes
                res.socket.setNoDelay(true)

                // set SSE headers
                setHeader(res, 'connection', 'keep-alive')
                setHeader(res, 'content-type', 'text/event-stream; charset=' + this.options.encoding)
                setHeader(res, 'cache-control', 'no-cache')

                if (!res.headersSent)
                    res.writeHead(200)
                else
                    self.emit('warning', 'headers are already sent', res)
            }

            res.write(message, 'utf8', function done() {
                  callback(null)
            })

            // force the partially-compressed response
            // to be flushed to the client
            if (compress)
                res.flush()
        });
    }
    return this
}
`

**Comment by schwarzkopfb** [comment]
Hey!

I'm sorry, I only had the time now to make the requested changes, but in the latest release (`0.5`) I added a new method (`broadcaster.send(...)`) which allows you to send events to a single client. Related documentation can be found [here](https://github.com/schwarzkopfb/sse-broadcast/blob/master/API.md#broadcastersendresponse-request-eventnameoroptions-data-callback).

Although this solution came a bit late, I honestly hope that it'll still be useful to you. Please let me know if you have any further questions, I'll be happy to answer them!

**Comment by araker** [comment]
Thanks for implementing this. One question though, did you tag your release? I don't get a new version with npm update and the release history of this repository is also empty.
